-- Full list of corrections as of Unicode 16.0.0
-- Taken from https://www.unicode.org/Public/UCD/latest/ucd/NameAliases.txt

require('strict')

local p = {}

p.aliases = {
    [0x01A2] = "LATIN CAPITAL LETTER GHA";
    [0x01A3] = "LATIN SMALL LETTER GHA";
    [0x0616] = "ARABIC SMALL HIGH LIGATURE ALEF WITH YEH BARREE";
    [0x0709] = "SYRIAC SUBLINEAR COLON SKEWED LEFT";
    [0x0CDE] = "KANNADA LETTER LLLA";
    [0x0E9D] = "LAO LETTER FO FON";
    [0x0E9F] = "LAO LETTER FO FAY";
    [0x0EA3] = "LAO LETTER RO";
    [0x0EA5] = "LAO LETTER LO";
    [0x0FD0] = "TIBETAN MARK BKA- SHOG GI MGO RGYAN";
    [0x11EC] = "HANGUL JONGSEONG YESIEUNG-KIYEOK";
    [0x11ED] = "HANGUL JONGSEONG YESIEUNG-SSANGKIYEOK";
    [0x11EE] = "HANGUL JONGSEONG SSANGYESIEUNG";
    [0x11EF] = "HANGUL JONGSEONG YESIEUNG-KHIEUKH";
    [0x1BBD] = "SUNDANESE LETTER ARCHAIC I";
    [0x2118] = "WEIERSTRASS ELLIPTIC FUNCTION";
    [0x2448] = "MICR ON US SYMBOL";
    [0x2449] = "MICR DASH SYMBOL";
    [0x2B7A] = "LEFTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE VERTICAL STROKE";
    [0x2B7C] = "RIGHTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE VERTICAL STROKE";
    [0xA015] = "YI SYLLABLE ITERATION MARK";
    [0xAA6E] = "MYANMAR LETTER KHAMTI LLA";
    [0xFE18] = "PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRACKET";
    [0x122D4] = "CUNEIFORM SIGN NU11 TENU";
    [0x122D5] = "CUNEIFORM SIGN NU11 OVER NU11 BUR OVER BUR";
    [0x12327] = "CUNEIFORM SIGN KALAM";
    [0x1680B] = "BAMUM LETTER PHASE-A MAEMGBIEE";
    [0x16E56] = "MEDEFAIDRIN CAPITAL LETTER H";
    [0x16E57] = "MEDEFAIDRIN CAPITAL LETTER NG";
    [0x16E76] = "MEDEFAIDRIN SMALL LETTER H";
    [0x16E77] = "MEDEFAIDRIN SMALL LETTER NG";
    [0x1B001] = "HENTAIGANA LETTER E-1";
    [0x1D0C5] = "BYZANTINE MUSICAL SYMBOL FTHORA SKLIRON CHROMA VASIS";
    [0x1E899] = "MENDE KIKAKUI SYLLABLE M172 MBO";
    [0x1E89A] = "MENDE KIKAKUI SYLLABLE M174 MBOO";
}

function p.alias(frame)
   local getArgs = require('Module:Arguments').getArgs
   return p._alias(tonumber(getArgs(frame)[1], 16))
end

function p._alias(x) -- search by value
   return p.aliases[x]
end

return p
